<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-11T09:59:44 CDT" name="Default suite" finished-at="2024-03-11T09:59:57 CDT" duration-ms="13971">
    <groups>
    </groups>
    <test started-at="2024-03-11T09:59:44 CDT" name="Default test" finished-at="2024-03-11T09:59:57 CDT" duration-ms="13971">
      <class name="applitools_UI_Test.Applitools_UI_Test">
        <test-method signature="setUp()[pri:0, instance:applitools_UI_Test.Applitools_UI_Test@79207381]" started-at="2024-03-11T09:59:44 CDT" name="setUp" finished-at="2024-03-11T09:59:57 CDT" duration-ms="13855" status="FAIL">
          <exception class="com.applitools.eyes.EyesException">
            <message>
              <![CDATA[no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=122.0.6261.112)]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.applitools.eyes.EyesException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=122.0.6261.112)
at com.applitools.eyes.selenium.CommandExecutor.eyesCheck(CommandExecutor.java:120)
at com.applitools.eyes.selenium.Eyes.checkDto(Eyes.java:480)
at com.applitools.eyes.selenium.Eyes.check(Eyes.java:464)
at com.applitools.eyes.selenium.Eyes.checkWindow(Eyes.java:1348)
at applitools_UI_Test.Applitools_UI_Test.setUp(Applitools_UI_Test.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.applitools.eyes.EyesException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- applitools_UI_Test.Applitools_UI_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
